### ISSUE TITLE
Schedule feature

### ISSUE THREAD

**Issue by 1mfaasj** [captn3m0/outliner#13]
Hi, thanks for your provided, docker solution!
Is it possible to add a schedule functionality to it? So for instance you define an cron in the environment
and at that times the run starts?

Thanks

--EDIT
Second thought: The exported file needs to have a date/timestamp or something. otherwise it fails or overwrites I guess.

**Comment by captn3m0** [comment]
I don't think adding a scheduler is in scope here. I haven't used this in a long time, but when I did run this in production, it was running the git sync over to GitHub, using a Kubernetes Cron Job as the scheduler.

You can run your docker container on a schedule using a systemd timer, or a cron job or something like that.
