### ISSUE TITLE
docker - export functionality all collections to a ZIP file

### ISSUE THREAD

**Issue by 1mfaasj** [captn3m0/outliner#14]
Hi, I'm using your provided docker solution and have one question about it.
It works when I execute an export but it creates a lot of separate .md files for each collection...

It would be great if you add an option to export all collections at once AS ZIP.
This way I'm able to import all collections with just one ZIP file.
is this something you can work on? 

Now I need to import all .md files one for for, that's not very practical. 

Thanks

**Comment by captn3m0** [comment]
Can't this be done with a simple wrapper script?

```
docker run ... /mnt/outliner-export
zip -qr /backups/outliner-$(date +"%y-%d-%m").zip /mnt/outliner-export
```
