### ISSUE TITLE
unzip: short read

### ISSUE THREAD

**Issue by rgstephens** [captn3m0/outliner#3]
Thanks for this tool.  When I try the export, I get this error and no output file:

```
unzip: short read
```

**Comment by captn3m0** [comment]
Guessing this was because of broken documentation, can you please retry this?

Or provide a failing command that I can use to debug?

**Comment by edersong** [comment]
Hello,
I'm facing the same issue:

`unzip: short read`

Command used:

`docker run -e OUTLINE_BASE_URI=https://outline.example.com -e OUTLINE_TOKEN=example -v /markdown:/data captn3m0/outliner export /data`
